### ISSUE TITLE
Why not use a standard protocol? 

### ISSUE THREAD

**Issue by davux** [Bit-Nation/chat-backend#6]
Maybe this has been discussed somewhere else, but I'm curious why we don't use a more standard messaging protocol such as e.g. Matrix (or XMPP, or SMTP, or...).

**Comment by marknuzz** [comment]
@davux Hi, I'm the new Head of Engineering for Bitnation. This is something we've been having a lot of discussions about internally. 

This was a decision that was made prior to my time at Bitnation. And it should have been communicated better, both externally and internally. I am of the opinion that re-inventing the wheel is not a great idea, and regardless of what features a chat protocol will have, Matrix looks to be a strong starting point, even if forked. 

Apologies for the vague answer. We haven't formally committed to anything yet but Matrix is a top contender.
